# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Md2pikchrs < Formula
  desc "cli tools to integrate into your development process for generate pikchrs diagrams"
  homepage "https://github.com/gebv/pikchr"
  version "1.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gebv/pikchr/releases/download/v1.0.1/pikchr_Darwin_x86_64.tar.gz"
    sha256 "97c05855ec142df80e511492a3cd9b20e589720d60fd532bb0eac401b81e7290"
  end

  def install
    bin.install "pikchr"
  end

  test do
    system "#{bin}/md2pikchrs -v"
  end
end
