# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Md2pikchrs < Formula
  desc "cli tools to integrate into your development process for generate pikchrs diagrams"
  homepage "https://github.com/gebv/pikchr"
  version "1.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gebv/pikchr/releases/download/v1.0.1/pikchr_Darwin_x86_64.tar.gz"
    sha256 "4ac773e552a72d990eb1cf6155fe42458ace595488d69466e79b159a3fd6e724"
  end

  def install
    bin.install "pikchr"
  end

  test do
    system "#{bin}/md5pikchrs -v"
  end
end
