# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsapTools < Formula
  desc "The asap-tools it is collection of tools to simplify daily monotonous monotonous cases. For syncing tasks between ClickUp teams and more."
  homepage "https://github.com/gebv/asap-tools"
  version "0.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gebv/asap-tools/releases/download/v0.0.2/asap-tools_Darwin_arm64.zip"
      sha256 "56d1712a14c6533422a282224aac066ea95054a1bcb407ddb381c25836376848"

      def install
        bin.install "asap-tools"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gebv/asap-tools/releases/download/v0.0.2/asap-tools_Darwin_x86_64.zip"
      sha256 "47cb3223ef909e50a88a642d6c0452f154e641752ea1858d0fb98f54af6b307b"

      def install
        bin.install "asap-tools"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/gebv/asap-tools/releases/download/v0.0.2/asap-tools_Linux_armv6.zip"
      sha256 "f832c039d6fec567fd71d3211a3efe18e1ff3faf24d6a6302eb7c230e5fc41a9"

      def install
        bin.install "asap-tools"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/gebv/asap-tools/releases/download/v0.0.2/asap-tools_Linux_x86_64.zip"
      sha256 "61f5055d309e2d114571c3fcedfe775235f7bebdbdf27c217ef3df0946bdd03b"

      def install
        bin.install "asap-tools"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gebv/asap-tools/releases/download/v0.0.2/asap-tools_Linux_arm64.zip"
      sha256 "acfb33705af3a64296a8447de76c7215dd80ddbf605a71fa25852872761400bb"

      def install
        bin.install "asap-tools"
      end
    end
  end

  test do
    system "#{bin}/asap-tools-cli -v"
  end
end
