# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Md2pikchrs < Formula
  desc "cli tools to integrate into your development process for generate pikchrs diagrams"
  homepage "https://github.com/gebv/pikchr"
  version "1.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gebv/pikchr/releases/download/v1.0.1/pikchr_Darwin_x86_64.tar.gz"
    sha256 "7a939c469997f7440a6c9acb1fce7476ea52dea4164ab9f6933d14f2dfb41d64"
  end

  def install
    bin.install "pikchr"
  end

  test do
    system "#{bin}/md2pikchrs -v"
  end
end
