# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Md2pikchrs < Formula
  desc "cli tools to integrate into your development process for generate pikchrs diagrams"
  homepage "https://github.com/gebv/pikchr"
  version "1.0.1"
  license "MIT"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/gebv/pikchr/releases/download/v1.0.1/pikchr_Darwin_x86_64.tar.gz"
    sha256 "6a1fcec96546312d67ce22c97d2b0bb59f4932786b13f5bc44827c26dbdda8b0"
  end

  def install
    bin.install "md2pikchrs"
  end

  test do
    system "#{bin}/md2pikchrs -v"
  end
end
